/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-08-06 14:02:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class btvn_005f3_005f6_005ftemplate_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private String tieuDe;
  private javax.servlet.jsp.tagext.JspFragment noiDung;

  public String getTieuDe() {
    return this.tieuDe;
  }

  public void setTieuDe(String tieuDe) {
    this.tieuDe = tieuDe;
    jspContext.setAttribute("tieuDe", tieuDe);
  }

  public javax.servlet.jsp.tagext.JspFragment getNoiDung() {
    return this.noiDung;
  }

  public void setNoiDung(javax.servlet.jsp.tagext.JspFragment noiDung) {
    this.noiDung = noiDung;
    jspContext.setAttribute("noiDung", noiDung);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getTieuDe() != null ) 
      _jspx_page_context.setAttribute("tieuDe", getTieuDe());
    if( getNoiDung() != null ) 
      _jspx_page_context.setAttribute("noiDung", getNoiDung());

    try {
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tieuDe }", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("header, footer {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100px;\n");
      out.write("	background-color: lightblue;\n");
      out.write("}\n");
      out.write("\n");
      out.write("main {\n");
      out.write("	display: flex;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav {\n");
      out.write("	width: 20%;\n");
      out.write("	background-color: khaki;\n");
      out.write("}\n");
      out.write("\n");
      out.write("article {\n");
      out.write("	width: 80%;\n");
      out.write("	background-color: lightyellow;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<h1>Header</h1>\n");
      out.write("	</header>\n");
      out.write("	<main>\n");
      out.write("		<nav>\n");
      out.write("			<h2>Thực đơn</h2>\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"chao.jsp\">Chào</a></li>\n");
      out.write("				<li><a href=\"btvn_3_4_upload-file\">Upload</a></li>\n");
      out.write("				<li><a href=\"#\">Link 3</a></li>\n");
      out.write("				<li><a href=\"#\">Link 4</a></li>\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("		<article>\n");
      out.write("			<h2>Nội dung</h2>\n");
      out.write("			");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getNoiDung() != null) {
        getNoiDung().invoke(_jspx_sout);
      }
      out.write("\n");
      out.write("		</article>\n");
      out.write("	</main>\n");
      out.write("	<footer>\n");
      out.write("	<h1>Footer</h1>\n");
      out.write("	</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
